security:
  basic:
    enabled: false
  oauth2:
#    sso:
#      loginPath: /login
#    client:
#      ##网关的地址
#      access-token-uri: http://localhost:9030/uaa/oauth/token
#      user-authorization-uri: http://localhost:9030/uaa/oauth/authorize
#      client-id: webApp
#      client-secret: webApp
    resource:
      user-info-uri:  http://localhost:8060/user
      prefer-token-info: false