server:
   port: 8101
   
spring:
  application:
    name: tax-config-server #配置服务名称
  profiles:
    active: native #设置为本地启动的方式，而不是通过git
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config   # 配置文件所在目录，classpath（类路径）和（系统文件路径） file两种
    
eureka:
   instance:
      prefer-ip-address: true
   client:
      serviceUrl:
         defaultZone: http://admin:admin@127.0.0.1:8100/eureka/